### ISSUE TITLE
Forking the SimulIDE software

### ISSUE THREAD

**Issue by Foadsf** [lemonpaul/SimulIDE#10]
I have been an advocate for SimulIDE and a Patreon of @Arcachofo for quite some time. I have been suggesting this software to many of my students, colleagues, and other people on the internet. As a veteran user of the software, I'm writing this message to express my anger and disappointment in the management of the project. 

- I have been begging @Arcachofo to move the project to GitHub or GitLab for a long time. Seriously who uses SVN and SourceForge anymore? If you don't want to rely on proprietary platforms, OK, self-host GitLab. But please please for the love of FSM do not use Patreon as a code distribution platform. It is the worst way of distributing code I have seen, ever!

- I have [asked](https://simulide.blogspot.com/p/forum.html) @Arcachofo to at least reactivate the SourceForge comments and ticketing. Nabble is garbage and no one wants to create new accounts just to leave a comment.

- Share your identity and an email. who is @Arcachofo ? how we are supposed to communicate with her/him? Googling this ID there is no information other than probably his name is "Santiago G." or something. For god's sake, you are developing an open-source software not a secret project for the CIA. People should know you and to be able to communicate with you directly. 

Anyway, given these issues. 48 hours from this comment I will fork the project and put it on GitHub. I hope before that the dev(s) consider the criticism and change the situation. 

Best,
Foad

**Comment by lemonpaul** [comment]
@Arcachofo don't support this repository. He even isn't interested in updating this package in debian repository. You can contact him on patreon or using mail santigoro@gmail.com
